// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgwfxxjtuowlhbxcoaca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnd2Z4eGp0dW93bGhieGNvYWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTM1MDgsImV4cCI6MjA1ODI4OTUwOH0.kk5ltbk97tHDM2xek-yKTiYW_kmKeMzs5ryPIfL67zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);