
export const mockProcurementTickets = [
  {
    id: "PR001",
    applicationName: "Slack",
    vendor: "Slack Technologies",
    requestedBy: "Jane Smith",
    requestDate: "2023-08-15",
    status: "Approved",
    priority: "Medium",
    department: "Engineering",
    businessJustification: "Our team needs a better communication tool for remote work. Slack will improve collaboration across engineering teams and reduce email volume.",
    annualCost: "$12,000",
  },
  {
    id: "PR002",
    applicationName: "Adobe Creative Cloud",
    vendor: "Adobe Inc.",
    requestedBy: "Michael Johnson",
    requestDate: "2023-09-01",
    status: "Pending",
    priority: "Low",
    department: "Marketing",
    businessJustification: "The marketing team needs access to professional design tools to create materials for upcoming campaigns.",
    annualCost: "$7,200",
  },
  {
    id: "PR003",
    applicationName: "Salesforce",
    vendor: "Salesforce Inc.",
    requestedBy: "Sarah Williams",
    requestDate: "2023-09-10",
    status: "In Review",
    priority: "High",
    department: "Sales",
    businessJustification: "We need a better CRM system to track our growing customer base and improve sales forecasting.",
    annualCost: "$24,000",
  },
  {
    id: "PR004",
    applicationName: "Jira",
    vendor: "Atlassian",
    requestedBy: "Thomas Brown",
    requestDate: "2023-09-18",
    status: "Rejected",
    priority: "Medium",
    department: "Product",
    businessJustification: "Rejected due to overlap with existing project management tools. We already have Asana licenses that can fulfill these requirements.",
    annualCost: "$8,400",
  },
  {
    id: "PR005",
    applicationName: "Zoom",
    vendor: "Zoom Video Communications",
    requestedBy: "Emily Davis",
    requestDate: "2023-09-25",
    status: "Approved",
    priority: "High",
    department: "Operations",
    businessJustification: "We need a reliable video conferencing tool for client meetings and internal communications as we expand our remote workforce.",
    annualCost: "$15,000",
  },
  {
    id: "PR006",
    applicationName: "QuickBooks",
    vendor: "Intuit",
    requestedBy: "Robert Wilson",
    requestDate: "2023-10-02",
    status: "Pending",
    priority: "Medium",
    department: "Finance",
    businessJustification: "Our accounting team needs better financial management software to track expenses and prepare for the upcoming fiscal year.",
    annualCost: "$5,500",
  },
  {
    id: "PR007",
    applicationName: "Asana",
    vendor: "Asana Inc.",
    requestedBy: "Jennifer Lee",
    requestDate: "2023-10-10",
    status: "In Review",
    priority: "Low",
    department: "Engineering",
    businessJustification: "Our team needs a project management tool to better organize tasks and deadlines for the upcoming product launch.",
    annualCost: "$9,600",
  },
];
